[package]
name = "stringer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
quick-xml = "0.36.1"
regex = "1.10.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
